INSERT INTO dayoff_master (name, dt)
SELECT
	'standard', DATEADD('DAY', A.d * 100 + B.d * 10 + C.d, CURRENT_DATE)
FROM
	((SELECT 0 AS d FROM dual) UNION ALL  (SELECT 1 FROM dual) UNION ALL  (SELECT 2 FROM dual) UNION ALL  (SELECT 3 FROM dual) UNION ALL  (SELECT 4 FROM dual) UNION ALL  (SELECT 5 FROM dual) UNION ALL  (SELECT 6 FROM dual) UNION ALL  (SELECT 7 FROM dual) UNION ALL  (SELECT 8 FROM dual) UNION ALL  (SELECT 9 FROM dual)) AS A,
	((SELECT 0 AS d FROM dual) UNION ALL  (SELECT 1 FROM dual) UNION ALL  (SELECT 2 FROM dual) UNION ALL  (SELECT 3 FROM dual) UNION ALL  (SELECT 4 FROM dual) UNION ALL  (SELECT 5 FROM dual) UNION ALL  (SELECT 6 FROM dual) UNION ALL  (SELECT 7 FROM dual) UNION ALL  (SELECT 8 FROM dual) UNION ALL  (SELECT 9 FROM dual)) AS B,
	((SELECT 0 AS d FROM dual) UNION ALL  (SELECT 1 FROM dual) UNION ALL  (SELECT 2 FROM dual) UNION ALL  (SELECT 3 FROM dual) UNION ALL  (SELECT 4 FROM dual) UNION ALL  (SELECT 5 FROM dual) UNION ALL  (SELECT 6 FROM dual) UNION ALL  (SELECT 7 FROM dual) UNION ALL  (SELECT 8 FROM dual) UNION ALL  (SELECT 9 FROM dual)) AS C
WHERE
	DAY_OF_WEEK(DATEADD('DAY', A.d * 100 + B.d * 10 + C.d, CURRENT_DATE)) IN (1, 7)
